"""patch_og_titles.py – Shorten og:title / twitter:title for pages that exceed 60 chars.
The <title> tag is left untouched (Google is fine with ~70 chars).
Safe to re-run."""
import re

TITLE_FIXES: dict[str, str] = {
    # File -> short og:title (<=60 chars, no '| LicenBase' suffix)
    "products.html":       "All Hosting Licenses \u2013 cPanel, LiteSpeed &amp; More",
    # Product pages are regenerated by generate_pages.py with og_title keys,
    # but patch here too in case someone runs this without regenerating.
    "cpanel-license.html":    "Cheap cPanel License \u2013 VPS &amp; Dedicated from $4/mo",
    "litespeed-license.html": "Cheap LiteSpeed License \u2013 2, 4, 8 Core from $4/mo",
    "whmcs-license.html":     "Cheap WHMCS License \u2013 $20 One-Time or $4/mo",
    "wp-squared-license.html": "Cheap WP Squared License \u2013 WordPress Hosting $4/mo",
}

def patch(filename: str, short_title: str) -> None:
    try:
        s = open(filename, encoding="utf-8", newline="").read()
    except FileNotFoundError:
        print(f"  skip (not found): {filename}")
        return

    changed = False

    # og:title
    def fix_og(m: re.Match) -> str:
        nonlocal changed
        if m.group(2) != short_title:
            changed = True
            return m.group(1) + short_title + m.group(3)
        return m.group(0)

    s = re.sub(
        r'(<meta property="og:title" content=")([^"]+)(" />)',
        fix_og, s, count=1
    )

    # twitter:title
    def fix_tw(m: re.Match) -> str:
        nonlocal changed
        if m.group(2) != short_title:
            changed = True
            return m.group(1) + short_title + m.group(3)
        return m.group(0)

    s = re.sub(
        r'(<meta name="twitter:title" content=")([^"]+)(" />)',
        fix_tw, s, count=1
    )

    if changed:
        open(filename, "w", encoding="utf-8", newline="").write(s)
        print(f"  patched  {filename}  ({len(short_title)}c)")
    else:
        print(f"  ok       {filename}")


print("Patching og:title / twitter:title lengths...")
for fname, title in TITLE_FIXES.items():
    patch(fname, title)
print("Done.")
